// <auto-generated />
using ApiRestAlchemy.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRestAlchemy.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220903072556_migra")]
    partial class migra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiRestAlchemy.Models.Genero", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genero", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Image = " ",
                            Nombre = "Aventura/Fantasia"
                        },
                        new
                        {
                            GenreId = 2,
                            Image = " ",
                            Nombre = "Infantil/Fantasia"
                        });
                });

            modelBuilder.Entity("ApiRestAlchemy.Models.PeliculaOserie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("FechaDeCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonajesAsociados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("PeliculaOserie", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Calificacion = 4,
                            FechaDeCreacion = "22/04/2001",
                            GenreId = 1,
                            Imagen = " ",
                            PersonajesAsociados = "Shrek,Burro,Fiora",
                            Titulo = "Shrek"
                        },
                        new
                        {
                            MovieId = 2,
                            Calificacion = 4,
                            FechaDeCreacion = "22/11/1995",
                            GenreId = 2,
                            Imagen = " ",
                            PersonajesAsociados = "Woody,Buzz Lightyear,Andy",
                            Titulo = "Toy Story"
                        });
                });

            modelBuilder.Entity("ApiRestAlchemy.Models.Personaje", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"), 1L, 1);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterId");

                    b.HasIndex("MovieId");

                    b.ToTable("Personaje", (string)null);

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Edad = 30,
                            Historia = "Un ogro llamado Shrek vive en su pantano, pero su preciada soledad se ve súbitamente interrumpida por la invasión de los ruidosos personajes de los cuentos de hadas",
                            Imagen = " ",
                            MovieId = 1,
                            Nombre = "Shrek",
                            Peso = "230kg"
                        },
                        new
                        {
                            CharacterId = 2,
                            Edad = 16,
                            Historia = " es un asno parlante que se convierte en el compañero de aventuras de Shrek y se hace su mejor amigo, aunque al principio el ogro no le soportaba y lo repudia, cuando Lord Farquaad decide eliminar a las criaturas mágicas del reino y su dueña decide entregarlo.",
                            Imagen = " ",
                            MovieId = 1,
                            Nombre = "Burro",
                            Peso = "200kg"
                        },
                        new
                        {
                            CharacterId = 3,
                            Edad = 17,
                            Historia = "Woody es un vaquero de juguete con una cuerda en la parte de atrás, que al tirar de ella dice frases tales como: Hay una serpiente en mi bota o Alguien ha envenenado el abrevadero. Woody es el juguete preferido de Andy,hasta que llega Buzz Lightyear",
                            Imagen = " ",
                            MovieId = 2,
                            Nombre = "Woody",
                            Peso = "160g"
                        },
                        new
                        {
                            CharacterId = 4,
                            Edad = 16,
                            Historia = " es un juguete con forma de guerrero espacial, el cual llega hasta las manos de Andy, un niño con una gran colección de juguetes. En casa de Andy conocerá al resto de juguetes como son Woody, el Sr. Patata o Rex, entre otros.",
                            Imagen = " ",
                            MovieId = 2,
                            Nombre = "Buzz Lightyear",
                            Peso = "1kg"
                        });
                });

            modelBuilder.Entity("ApiRestAlchemy.Models.PeliculaOserie", b =>
                {
                    b.HasOne("ApiRestAlchemy.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("ApiRestAlchemy.Models.Personaje", b =>
                {
                    b.HasOne("ApiRestAlchemy.Models.PeliculaOserie", "PeliculaOserie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeliculaOserie");
                });
#pragma warning restore 612, 618
        }
    }
}
